# Use the specified Python image
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy requirements file and install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir tensorflow Flask numpy Pillow

# Copy the rest of the application code
COPY . /app

# Expose the port the app runs on
EXPOSE 5000

# Command to run the server
CMD ["python", "predict.py"]